My_data <- read.csv(file.choose())
View(My_data)
View(My_data)
mincolumns <- My_data %>% select(Product.type, Price, Revenue.generated, Manufacturing.costs, Shipping.costs)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(Hmisc)
mincolumns <- My_data %>% select(Product.type, Price, Revenue.generated, Manufacturing.costs, Shipping.costs)
 minrows <- mydata %>% slice(1,2,3,4,5,8,9,20,21)
minrows <- mydata %>% slice(1,2,3,4,5,8,9,20,21)
minrows <- my_data %>% slice(1,2,3,4,5,8,9,20,21)
minrows <- My_data %>% slice(1,2,3,4,5,8,9,20,21)
Sample <- My_data %>% sample_n(10)
View(Sample)
arrange <- Sample %>% arrange(Number.of.products.sold)
View(arrange)
View(My_data)
filtered_data <- My_data %>% filter(Revenue.generated > 5000)
View(filtered_data)
missing_values <-  is.na(17)
View(Sample)
missing_count <-sum(is.na(17))
missing_mean <-  mean(is.na(17))
my_data_no_na <- na.omit(My_data)
View(my_data_no_na)
mean(My_data$Price , na.rm = TRUE)
complete_cases <- mydata[complete.cases(My_data), ]
complete_cases <- My_data[complete.cases(My_data), ]
View(complete_cases)
cleaned_data <- na.omit(My_data)
glimpse(My_data)
boxplot_stats_result <- boxplot.stats(10)
View(boxplot_stats_result)
boxplot(7, main = "Box-and-Whisker Plot", ylab = "Values")
boxplot(7, main = "Box-and-Whisker Plot", ylab = "Values")
mean_age <- mean(My_data$Number.of.products.sold, na.rm = TRUE)
median_age <- median(mydata$Number.of.products.sold, na.rm = TRUE)
median_age <- median(My_data$Number.of.products.sold, na.rm = TRUE)
library(ggplot2)

       geom_point()ggplot(data = My_data, aes(x = Shipping.times, y = Lead.times )) + 
 ggplot(data = My_data, aes(x = Availability, y = Price)) + 
      geom_line()
ggplot(data = My_data, aes(x = Customer.demographics, y = Lead.times)) + 
       geom_bar()
barplot(table(My_data$Inspection.results))

summary(My_data)
cor(My_data$Number.of.products.sold, My_data$Costs)
scale(My_data$Order.quantities)
install.packages("caret")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("randomForest")
install.packages("rpart")
install.packages("e1071")
library(caret)
library(dplyr)
library(ggplot2)
library(randomForest)
library(rpart)
library(e1071)
My_data <- read.csv(file.choose())
str(My_data)
summary(My_data)
head(My_data)
model <- rpart(Number.of.products.sold ~ ., data = My_data)
print(model)
summary(model)
plot(model)
install.packages("randomForest")
library(randomForest)
model <- randomForest(Availability ~ Production.volumes, data = My_data)
predictions <- predict(model, newdata = My_data)
mse <- mean((predictions - My_data$Availability)^2)
install.packages("stats")
library(stats)
model <- lm(Revenue.generated ~ Number.of.products.sold, data = My_data)
predictions <- predict(model, newdata = My_data)
mse2 <- mean((predictions - My_data$Revenue.generated)^2)
library(class)
install.packages("kknn")
library(kknn)
model <- kknn(Costs ~ ., train = My_data, test = My_data, k = 2)
predictions <- fitted(model)
mse3 <- mean((predictions - My_data$Costs)^2)
install.packages("rpart")
library(rpart)
model <- rpart(Costs ~ ., data = My_data)
predictions <- predict(model, newdata = My_data)
mse4 <- mean((predictions - My_data$Costs)^2)
